// Copyright 2025.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//go:build zh

package ui

func GetFieldHelpZH(fieldName string) *FieldHelp {
	if help, exists := fieldHelpDataZH[fieldName]; exists {
		defaultValue := GetSSHFieldDefault(fieldName)
		if defaultValue != "" {
			help.Default = formatDefaultValue(fieldName, defaultValue)
		}
		return &help
	}
	return nil
}

// GetFieldHelp zh build version (build tag: zh)
func GetFieldHelp(fieldName string) *FieldHelp {
	return GetFieldHelpZH(fieldName)
}

var fieldHelpDataZH = map[string]FieldHelp{
	"Alias": {
		Field:       "别名",
		Description: "主机的昵称或缩写，这是你输入'ssh'命令后使用的名称。",
		Syntax:      "不含空格的任意字符串",
		Examples:    []string{"myserver", "prod-db", "dev-web-01"},
		Default:     "(必填)",
		Category:    "Basic",
	},
	"Host": {
		Field:       "主机",
		Description: "要连接的真实主机名或IP地址，可以是域名或IP地址。",
		Syntax:      "主机名 | IP地址",
		Examples:    []string{"example.com", "192.168.1.100", "2001:db8::1"},
		Default:     "(必填)",
		Category:    "Basic",
	},
	"Port": {
		Field:       "端口",
		Description: "远程主机上要连接的端口号，标准SSH端口是22。",
		Syntax:      "端口号 (1-65535)",
		Examples:    []string{"22", "2222", "8022"},
		Default:     "22",
		Category:    "Basic",
	},
	"User": {
		Field:       "用户",
		Description: "登录远程机器的用户名，如未指定则使用当前用户名。",
		Syntax:      "用户名",
		Examples:    []string{"root", "ubuntu", "admin", "deploy"},
		Default:     "当前用户名",
		Category:    "Basic",
	},
	"Keys": {
		Field:       "密钥",
		Description: "用于认证的SSH私钥文件路径，可指定多个密钥。",
		Syntax:      "路径[,路径,...]",
		Examples:    []string{"~/.ssh/id_ed25519", "~/.ssh/id_rsa,~/.ssh/id_ed25519"},
		Default:     "~/.ssh/id_rsa, ~/.ssh/id_ed25519 等",
		Category:    "Basic",
	},
	"Tags": {
		Field:       "标签",
		Description: "用于组织和筛选服务器的自定义标签，逗号分隔。",
		Syntax:      "标签1[,标签2,...]",
		Examples:    []string{"production", "development,staging", "web,frontend"},
		Default:     "无",
		Category:    "Basic",
	},
	"ProxyJump": {
		Field:       "代理跳板",
		Description: "指定一个或多个跳板机(堡垒主机)来到达目标服务器，用于访问防火墙后的服务器。",
		Syntax:      "[用户@]主机[:端口][,[用户@]主机[:端口]]",
		Examples:    []string{"bastion.example.com", "jump1.com,jump2.com", "user@proxy:2222"},
		Default:     "无",
		Since:       "OpenSSH 7.3+",
		Category:    "Connection",
	},
	"ProxyCommand": {
		Field:       "代理命令",
		Description: "用于连接服务器的命令，适用于通过代理或自定义连接方式连接。",
		Syntax:      "命令",
		Examples:    []string{"ssh -W %h:%p jump.example.com", "nc -X 5 -x proxy:1080 %h %p"},
		Default:     "无",
		Category:    "Connection",
	},
	"RemoteCommand": {
		Field:       "远程命令",
		Description: "成功连接后在远程机器上执行的命令。",
		Syntax:      "命令 | 无",
		Examples:    []string{"tmux attach || tmux new", "screen -r", "无"},
		Default:     "无",
		Since:       "OpenSSH 7.6+",
		Category:    "Connection",
	},
	"ConnectTimeout": {
		Field:       "连接超时",
		Description: "建立连接的超时秒数，适用于慢速或不稳定网络。",
		Syntax:      "秒数 | 无",
		Examples:    []string{"10", "30", "无"},
		Default:     "无(系统默认)",
		Category:    "Connection",
	},
	"ConnectionAttempts": {
		Field:       "连接尝试",
		Description: "放弃连接前尝试的次数。",
		Syntax:      "次数",
		Examples:    []string{"1", "3", "5"},
		Default:     "1",
		Category:    "Connection",
	},
	"SessionType": {
		Field:       "会话类型",
		Description: "请求的会话类型，'无会话'(-N标志)适用于无需shell的端口转发。",
		Syntax:      "无会话 | 子系统 | 默认",
		Examples:    []string{"无会话", "子系统", "默认"},
		Default:     "默认",
		Since:       "OpenSSH 8.7+",
		Category:    "Connection",
	},
	"RequestTTY": {
		Field:       "请求TTY",
		Description: "为会话请求伪终端，交互式程序需要此项。",
		Syntax:      "是 | 否 | 强制 | 自动",
		Examples:    []string{"是", "强制", "自动"},
		Default:     "自动",
		Category:    "Connection",
	},
	"LocalForward": {
		Field:       "本地转发",
		Description: "将本地端口转发到远程地址，适用于通过SSH隧道访问远程服务。",
		Syntax:      "[绑定地址:]端口:主机:主机端口",
		Examples:    []string{"8080:localhost:80", "3306:db.internal:3306", "*:8080:localhost:80"},
		Default:     "无",
		Category:    "Forwarding",
	},
	"RemoteForward": {
		Field:       "远程转发",
		Description: "将远程端口转发到本地地址，允许远程用户访问本地服务。",
		Syntax:      "[绑定地址:]端口:主机:主机端口",
		Examples:    []string{"8080:localhost:3000", "*:80:localhost:8080"},
		Default:     "无",
		Category:    "Forwarding",
	},
	"DynamicForward": {
		Field:       "动态转发",
		Description: "在指定端口创建SOCKS代理，适用于通过SSH路由流量。",
		Syntax:      "[绑定地址:]端口",
		Examples:    []string{"1080", "localhost:1080", "*:1080"},
		Default:     "无",
		Category:    "Forwarding",
	},
	"ForwardAgent": {
		Field:       "转发Agent",
		Description: "将SSH agent连接转发到远程主机，允许在远程服务器使用本地SSH密钥。",
		Syntax:      "是 | 否",
		Examples:    []string{"是", "否"},
		Default:     "否",
		Category:    "Forwarding",
	},
	"ForwardX11": {
		Field:       "转发X11",
		Description: "启用X11转发，用于SSH上的GUI应用程序。",
		Syntax:      "是 | 否",
		Examples:    []string{"是", "否"},
		Default:     "否",
		Category:    "Forwarding",
	},
	"PubkeyAuthentication": {
		Field:       "公钥认证",
		Description: "启用或禁用公钥认证。",
		Syntax:      "是 | 否",
		Examples:    []string{"是", "否"},
		Default:     "是",
		Category:    "Authentication",
	},
	"PasswordAuthentication": {
		Field:       "密码认证",
		Description: "启用或禁用密码认证。",
		Syntax:      "是 | 否",
		Examples:    []string{"是", "否"},
		Default:     "是",
		Category:    "Authentication",
	},
	"PreferredAuthentications": {
		Field:       "首选认证方式",
		Description: "尝试的认证方法顺序。",
		Syntax:      "方法[,方法,...]",
		Examples:    []string{"publickey,password", "publickey,keyboard-interactive,password"},
		Default:     "gssapi-with-mic,hostbased,publickey,keyboard-interactive,password",
		Category:    "Authentication",
	},
	"IdentitiesOnly": {
		Field:       "仅使用指定密钥",
		Description: "仅使用ssh_config中配置的认证密钥文件，忽略ssh-agent。",
		Syntax:      "是 | 否",
		Examples:    []string{"是", "否"},
		Default:     "否",
		Category:    "Authentication",
	},
	"AddKeysToAgent": {
		Field:       "添加密钥到Agent",
		Description: "使用密钥时自动添加到ssh-agent。",
		Syntax:      "是 | 否 | 询问 | 确认",
		Examples:    []string{"是", "询问", "确认"},
		Default:     "否",
		Since:       "OpenSSH 7.2+",
		Category:    "Authentication",
	},
	"ControlMaster": {
		Field:       "控制主连接",
		Description: "启用连接多路复用，复用现有连接以提高速度。",
		Syntax:      "是 | 否 | 询问 | 自动 | 自动询问",
		Examples:    []string{"自动", "是", "否"},
		Default:     "否",
		Category:    "Multiplexing",
	},
	"ControlPath": {
		Field:       "控制路径",
		Description: "连接多路复用的控制套接字路径。",
		Syntax:      "路径",
		Examples:    []string{"~/.ssh/master-%r@%h:%p", "/tmp/ssh-%r@%h:%p"},
		Default:     "无",
		Category:    "Multiplexing",
	},
	"ControlPersist": {
		Field:       "控制持久化",
		Description: "初始客户端退出后在后台保持主连接。",
		Syntax:      "是 | 否 | 时间",
		Examples:    []string{"是", "10m", "4h", "否"},
		Default:     "否",
		Category:    "Multiplexing",
	},
	"ServerAliveInterval": {
		Field:       "服务器存活间隔",
		Description: "保活消息之间的秒数，防止空闲连接断开。",
		Syntax:      "秒数",
		Examples:    []string{"60", "120", "300"},
		Default:     "0(禁用)",
		Category:    "Keep-Alive",
	},
	"ServerAliveCountMax": {
		Field:       "服务器存活计数上限",
		Description: "断开连接前发送的保活消息数量。",
		Syntax:      "次数",
		Examples:    []string{"3", "5", "10"},
		Default:     "3",
		Category:    "Keep-Alive",
	},
	"TCPKeepAlive": {
		Field:       "TCP保活",
		Description: "发送TCP保活消息以检测断开的连接。",
		Syntax:      "是 | 否",
		Examples:    []string{"是", "否"},
		Default:     "是",
		Category:    "Keep-Alive",
	},
	"StrictHostKeyChecking": {
		Field:       "严格主机密钥检查",
		Description: "如何处理未知主机密钥，'询问'提示用户，'否'自动添加，'是'需要预先存在的密钥。",
		Syntax:      "是 | 否 | 询问 | 接受新",
		Examples:    []string{"询问", "接受新", "是"},
		Default:     "询问",
		Category:    "Security",
	},
	"UserKnownHostsFile": {
		Field:       "用户已知主机文件",
		Description: "存储主机密钥的文件，可指定多个文件。",
		Syntax:      "路径 [路径 ...]",
		Examples:    []string{"~/.ssh/known_hosts", "~/.ssh/known_hosts ~/.ssh/known_hosts2"},
		Default:     "~/.ssh/known_hosts",
		Category:    "Security",
	},
	"HostKeyAlgorithms": {
		Field:       "主机密钥算法",
		Description: "主机密钥算法的偏好顺序，使用+/+从默认中添加/删除。",
		Syntax:      "算法[,算法,...] | +算法 | -算法",
		Examples:    []string{"ssh-ed25519,ssh-rsa", "+ssh-rsa", "-ssh-dss"},
		Default:     "ssh-ed25519,ecdsa-sha2-nistp256,ssh-rsa,...",
		Category:    "Security",
	},
	"Ciphers": {
		Field:       "加密算法",
		Description: "加密算法的偏好顺序。",
		Syntax:      "算法[,算法,...] | +算法 | -算法",
		Examples:    []string{"aes256-gcm@openssh.com,aes256-ctr", "+aes256-cbc", "-3des-cbc"},
		Default:     "chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,...",
		Category:    "Security",
	},
	"MACs": {
		Field:       "MAC算法",
		Description: "消息认证码算法的偏好顺序。",
		Syntax:      "算法[,算法,...] | +算法 | -算法",
		Examples:    []string{"hmac-sha2-256,hmac-sha2-512", "+hmac-md5", "-hmac-sha1"},
		Default:     "umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,...",
		Category:    "Security",
	},
	"LogLevel": {
		Field:       "日志级别",
		Description: "日志详细程度，更高级别显示更多调试细节。",
		Syntax:      "QUIET | FATAL | ERROR | INFO | VERBOSE | DEBUG | DEBUG1 | DEBUG2 | DEBUG3",
		Examples:    []string{"INFO", "DEBUG", "ERROR"},
		Default:     "INFO",
		Category:    "Debugging",
	},
	"Compression": {
		Field:       "压缩",
		Description: "启用压缩以减少带宽使用，适用于慢速连接。",
		Syntax:      "是 | 否",
		Examples:    []string{"是", "否"},
		Default:     "否",
		Category:    "Connection",
	},
	"BatchMode": {
		Field:       "批处理模式",
		Description: "禁用所有交互式提示，适用于脚本和自动化。",
		Syntax:      "是 | 否",
		Examples:    []string{"是", "否"},
		Default:     "否",
		Category:    "Connection",
	},
	"IPQoS": {
		Field:       "IP服务质量",
		Description: "SSH连接的QoS/DSCP/TOS设置，可为交互和批量流量指定不同值。",
		Syntax:      "dscp值 | 低延迟 | 吞吐量 | 可靠性 | af11-af43 | cs0-cs7 | ef | le",
		Examples:    []string{"af21 cs1", "lowdelay throughput", "cs2"},
		Default:     "af21 cs1",
		Category:    "Connection",
	},
	"BindAddress": {
		Field:       "绑定地址",
		Description: "使用特定源地址进行连接，适用于多网络接口主机。",
		Syntax:      "地址 | 主机名",
		Examples:    []string{"192.168.1.100", "localhost", "*"},
		Default:     "无",
		Category:    "Connection",
	},
	"BindInterface": {
		Field:       "绑定接口",
		Description: "使用特定网络接口进行连接，适用于通过特定网卡路由。",
		Syntax:      "接口名",
		Examples:    []string{"eth0", "en0", "wlan0"},
		Default:     "无",
		Since:       "OpenSSH 7.7+",
		Category:    "Connection",
	},
	"AddressFamily": {
		Field:       "地址族",
		Description: "限制连接到IPv4或IPv6地址。",
		Syntax:      "任意 | inet | inet6",
		Examples:    []string{"任意", "inet", "inet6"},
		Default:     "任意",
		Category:    "Connection",
	},
	"CanonicalizeHostname": {
		Field:       "规范化主机名",
		Description: "控制是否执行主机名规范化，适用于缩短主机名。",
		Syntax:      "是 | 否 | 始终",
		Examples:    []string{"是", "否", "始终"},
		Default:     "否",
		Since:       "OpenSSH 6.5+",
		Category:    "Connection",
	},
	"CanonicalDomains": {
		Field:       "规范域名",
		Description: "主机名规范化的搜索域，SSH会尝试添加这些域名。",
		Syntax:      "域名1[,域名2,...]",
		Examples:    []string{"example.com", "internal.net,example.org"},
		Default:     "无",
		Since:       "OpenSSH 6.5+",
		Category:    "Connection",
	},
	"CanonicalizeFallbackLocal": {
		Field:       "规范化回退本地",
		Description: "规范化失败时是否回退，'是'则使用原始主机名。",
		Syntax:      "是 | 否",
		Examples:    []string{"是", "否"},
		Default:     "是",
		Since:       "OpenSSH 6.5+",
		Category:    "Connection",
	},
	"CanonicalizeMaxDots": {
		Field:       "规范化最大点数",
		Description: "禁用规范化前主机名中允许的最大点数。",
		Syntax:      "次数",
		Examples:    []string{"1", "2", "0"},
		Default:     "1",
		Since:       "OpenSSH 6.5+",
		Category:    "Connection",
	},
	"CanonicalizePermittedCNAMEs": {
		Field:       "允许的CNAME",
		Description: "规范化期间CNAME跟随的规则。",
		Syntax:      "源:目标[,源:目标,...]",
		Examples:    []string{"*.example.com:example.net", "*.internal:*.example.com"},
		Default:     "无",
		Since:       "OpenSSH 6.5+",
		Category:    "Connection",
	},
	"ForwardX11Trusted": {
		Field:       "可信X11转发",
		Description: "启用可信X11转发，安全性较低但兼容性更好。",
		Syntax:      "是 | 否",
		Examples:    []string{"是", "否"},
		Default:     "否",
		Category:    "Forwarding",
	},
	"ClearAllForwardings": {
		Field:       "清除所有转发",
		Description: "清除配置文件中设置的所有端口转发。",
		Syntax:      "是 | 否",
		Examples:    []string{"是", "否"},
		Default:     "否",
		Category:    "Forwarding",
	},
	"ExitOnForwardFailure": {
		Field:       "转发失败退出",
		Description: "端口转发失败时终止连接。",
		Syntax:      "是 | 否",
		Examples:    []string{"是", "否"},
		Default:     "否",
		Category:    "Forwarding",
	},
	"GatewayPorts": {
		Field:       "网关端口",
		Description: "允许远程主机连接到转发端口。",
		Syntax:      "是 | 否 | 客户端指定",
		Examples:    []string{"否", "是", "客户端指定"},
		Default:     "否",
		Category:    "Forwarding",
	},
	"KbdInteractiveAuthentication": {
		Field:       "键盘交互认证",
		Description: "启用键盘交互认证（例如用于双因素认证）。",
		Syntax:      "是 | 否",
		Examples:    []string{"是", "否"},
		Default:     "是",
		Category:    "Authentication",
	},
	"NumberOfPasswordPrompts": {
		Field:       "密码提示次数",
		Description: "放弃前密码提示的次数。",
		Syntax:      "次数",
		Examples:    []string{"3", "1", "5"},
		Default:     "3",
		Category:    "Authentication",
	},
	"IdentityAgent": {
		Field:       "认证Agent",
		Description: "认证agent套接字的位置。",
		Syntax:      "路径 | SSH_AUTH_SOCK | 无",
		Examples:    []string{"SSH_AUTH_SOCK", "~/.ssh/agent.sock", "无"},
		Default:     "SSH_AUTH_SOCK",
		Since:       "OpenSSH 7.3+",
		Category:    "Authentication",
	},
	"PubkeyAcceptedAlgorithms": {
		Field:       "公钥接受算法",
		Description: "公钥认证接受的签名算法。",
		Syntax:      "算法[,算法,...]",
		Examples:    []string{"ssh-ed25519,ssh-rsa", "+ssh-rsa", "-ssh-dss"},
		Default:     "(所有支持的)",
		Since:       "OpenSSH 8.5+",
		Category:    "Authentication",
	},
	"HostbasedAcceptedAlgorithms": {
		Field:       "主机认证接受算法",
		Description: "主机认证接受的签名算法。",
		Syntax:      "算法[,算法,...]",
		Examples:    []string{"ssh-ed25519,ssh-rsa", "+ssh-rsa", "-ssh-dss"},
		Default:     "(所有支持的)",
		Since:       "OpenSSH 8.5+",
		Category:    "Authentication",
	},
	"CheckHostIP": {
		Field:       "检查主机IP",
		Description: "在known_hosts文件中检查主机IP地址。",
		Syntax:      "是 | 否",
		Examples:    []string{"是", "否"},
		Default:     "否",
		Category:    "Security",
	},
	"FingerprintHash": {
		Field:       "指纹哈希",
		Description: "显示密钥指纹的哈希算法。",
		Syntax:      "md5 | sha256",
		Examples:    []string{"sha256", "md5"},
		Default:     "sha256",
		Since:       "OpenSSH 6.8+",
		Category:    "Security",
	},
	"VerifyHostKeyDNS": {
		Field:       "DNS验证主机密钥",
		Description: "使用DNS SSHFP记录验证主机密钥。",
		Syntax:      "是 | 否 | 询问",
		Examples:    []string{"否", "询问", "是"},
		Default:     "否",
		Category:    "Security",
	},
	"UpdateHostKeys": {
		Field:       "更新主机密钥",
		Description: "自动使用新主机密钥更新known_hosts。",
		Syntax:      "是 | 否 | 询问",
		Examples:    []string{"否", "询问", "是"},
		Default:     "否",
		Since:       "OpenSSH 6.8+",
		Category:    "Security",
	},
	"HashKnownHosts": {
		Field:       "哈希已知主机",
		Description: "在known_hosts文件中哈希主机名和地址。",
		Syntax:      "是 | 否",
		Examples:    []string{"否", "是"},
		Default:     "否",
		Category:    "Security",
	},
	"VisualHostKey": {
		Field:       "可视化主机密钥",
		Description: "显示主机密钥的ASCII艺术表示。",
		Syntax:      "是 | 否",
		Examples:    []string{"否", "是"},
		Default:     "否",
		Category:    "Security",
	},
	"KexAlgorithms": {
		Field:       "密钥交换算法",
		Description: "使用的密钥交换算法。",
		Syntax:      "算法[,算法,...]",
		Examples:    []string{"curve25519-sha256", "+diffie-hellman-group14-sha256", "-ecdh-sha2-nistp256"},
		Default:     "(所有支持的)",
		Category:    "Cryptography",
	},
	"LocalCommand": {
		Field:       "本地命令",
		Description: "连接后在本地机器执行的命令。",
		Syntax:      "命令",
		Examples:    []string{"echo '已连接到 %h'", "notify-send 'SSH已连接'"},
		Default:     "无",
		Category:    "Command",
	},
	"PermitLocalCommand": {
		Field:       "允许本地命令",
		Description: "允许执行本地命令。",
		Syntax:      "是 | 否",
		Examples:    []string{"否", "是"},
		Default:     "否",
		Category:    "Command",
	},
	"EscapeChar": {
		Field:       "转义字符",
		Description: "SSH会话的转义字符（默认为~），设置为'无'则禁用。",
		Syntax:      "字符 | 无 | ^字符",
		Examples:    []string{"~", "^", "无"},
		Default:     "~",
		Category:    "Command",
	},
	"SendEnv": {
		Field:       "发送环境变量",
		Description: "发送到服务器的环境变量。",
		Syntax:      "变量[,变量,...]",
		Examples:    []string{"LANG", "LC_*", "TERM", "LANG LC_* EDITOR"},
		Default:     "无",
		Category:    "Environment",
	},
	"SetEnv": {
		Field:       "设置环境变量",
		Description: "为SSH会话设置的环境变量。",
		Syntax:      "变量=值[,变量=值,...]",
		Examples:    []string{"FOO=bar", "DEBUG=1", "PATH=/custom/path:$PATH"},
		Default:     "无",
		Since:       "OpenSSH 7.8+",
		Category:    "Environment",
	},
}